import React, { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import axios from 'axios';
import { FiEdit2, FiPlus, FiTrash2, FiUpload, FiX } from 'react-icons/fi';
import './AdminProducts.css';

const api = 'http://localhost:3000';
const auth = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem('token') || JSON.parse(localStorage.getItem('user') || 'null')?._id || ''}` } });
const blank = { name: '', price: '', category: '', image: '', description: '', countInStock: '' };
const imageSrc = image => image?.startsWith('/') ? `${api}${image}` : image;

export const AdminProducts = () => {
  const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [form, setForm] = useState(blank); const [file, setFile] = useState(null); const [editing, setEditing] = useState(null); const [error, setError] = useState('');
  const load = async () => { const [productsRes, categoriesRes] = await Promise.all([axios.get(`${api}/api/products`), axios.get(`${api}/api/categories`)]); setProducts(productsRes.data); setCategories(categoriesRes.data); };
  useEffect(() => { load().catch(() => setError('Unable to load products.')); }, []);
  const close = () => { setEditing(null); setFile(null); setForm(blank); setError(''); };
  const chooseFile = selected => selected?.type?.startsWith('image/') && setFile(selected);
  const save = async event => { event.preventDefault(); setError(''); try { const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, value)); if (file) data.set('image', file); await axios[editing ? 'put' : 'post'](`${api}/admin/product${editing ? `/${editing}` : ''}`, data, auth()); close(); load(); } catch (err) { setError(err.response?.data?.message || 'Unable to save product.'); } };
  const edit = product => { setEditing(product._id); setForm({ ...product, category: product.category?._id || product.category, countInStock: product.countInStock ?? 0 }); };
  const remove = async id => { if (window.confirm('Delete this product?')) { await axios.delete(`${api}/admin/product/${id}`, auth()); load(); } };
  const preview = file ? URL.createObjectURL(file) : imageSrc(form.image);
  return <main className="admin-products"><header className="page-header"><div><h1>Products</h1><p>Manage catalogue images and available stock.</p></div><button className="add-btn" onClick={() => setEditing('new')}><FiPlus /> Add product</button></header>{error && !editing && <p className="form-error">{error}</p>}
    <div className="table-container"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Actions</th></tr></thead><tbody>{products.map(product => <tr key={product._id}><td className="product-cell">{product.image && <img src={imageSrc(product.image)} alt="" />}<span>{product.name}</span></td><td>{product.category?.name || 'Uncategorized'}</td><td>${Number(product.price).toFixed(2)}</td><td><b className={product.countInStock ? 'stock-ok' : 'stock-out'}>{product.countInStock || 0}</b></td><td className="actions"><button onClick={() => edit(product)}><FiEdit2 /></button><button className="danger" onClick={() => remove(product._id)}><FiTrash2 /></button></td></tr>)}{!products.length && <tr><td colSpan="5">No products created yet.</td></tr>}</tbody></table></div>
    <AnimatePresence>{editing && <motion.div className="modal-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={close}><motion.form className="modal product-form" initial={{ scale: .95, y: 16 }} animate={{ scale: 1, y: 0 }} onClick={event => event.stopPropagation()} onSubmit={save}><div className="modal-head"><h2>{editing === 'new' ? 'Add' : 'Edit'} product</h2><button type="button" onClick={close}><FiX /></button></div><div className="form-row"><input placeholder="Product name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /><input type="number" min="0" step="0.01" placeholder="Price" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} required /></div><div className="form-row"><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} required><option value="">Select category</option>{categories.map(category => <option key={category._id} value={category._id}>{category.name}</option>)}</select><input type="number" min="0" step="1" placeholder="Stock quantity" value={form.countInStock} onChange={e => setForm({ ...form, countInStock: e.target.value })} required /></div><input placeholder="Image URL (optional if uploading)" value={form.image} onChange={e => setForm({ ...form, image: e.target.value })} /><label className="image-drop" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); chooseFile(e.dataTransfer.files[0]); }} onPaste={e => chooseFile([...e.clipboardData.items].find(item => item.type.startsWith('image/'))?.getAsFile())}><input type="file" accept="image/*" onChange={e => chooseFile(e.target.files[0])} /><FiUpload /> Drop, upload, or paste an image{preview && <img src={preview} alt="Product preview" />}</label><textarea placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} />{error && <p className="form-error">{error}</p>}<button className="save-btn">{editing === 'new' ? 'Create product' : 'Save changes'}</button></motion.form></motion.div>}</AnimatePresence>
  </main>;
};
