import React, { useEffect, useMemo, useState } from 'react';
import { Line } from 'react-chartjs-2';
import axios from 'axios';
import { Chart as ChartJS, CategoryScale, Filler, Legend, LineElement, LinearScale, PointElement, Tooltip } from 'chart.js';
import { FiDollarSign, FiPackage, FiRefreshCw, FiShoppingCart, FiTrendingUp, FiUsers } from 'react-icons/fi';
import './AdminDashboard.css';
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Tooltip, Legend, Filler);

const api = 'http://localhost:3000'; const auth = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem('token') || JSON.parse(localStorage.getItem('user') || 'null')?._id || ''}` } });
const money = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value || 0);
const label = date => new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(`${date}T00:00:00`));

export const AdminDashboard = () => {
  const [sales, setSales] = useState([]), [users, setUsers] = useState(0), [products, setProducts] = useState(0), [range, setRange] = useState(30), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const [salesRes, usersRes, productsRes] = await Promise.all([axios.get(`${api}/admin/sales-graph`, auth()), axios.get(`${api}/admin/users`, auth()), axios.get(`${api}/api/products`)]); setSales(salesRes.data); setUsers(usersRes.data?.length || 0); setProducts(productsRes.data?.length || 0); } catch { setError('Unable to load live sales data.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const points = useMemo(() => sales.slice(-range), [sales, range]); const revenue = points.reduce((sum, point) => sum + point.revenue, 0); const orders = points.reduce((sum, point) => sum + point.count, 0); const average = orders ? revenue / orders : 0;
  const chartData = { labels: points.map(point => label(point._id)), datasets: [{ label: 'Sales', data: points.map(point => point.revenue), borderColor: '#167a60', backgroundColor: 'rgba(35, 180, 132, .14)', borderWidth: 3, fill: true, tension: .38, pointRadius: 0, pointHoverRadius: 6, pointHoverBackgroundColor: '#167a60', pointHoverBorderColor: '#fff', pointHoverBorderWidth: 3 }] };
  const options = { responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: 'index' }, plugins: { legend: { display: false }, tooltip: { displayColors: false, padding: 13, backgroundColor: '#173a2e', titleFont: { size: 12 }, bodyFont: { size: 17, weight: 'bold' }, callbacks: { title: items => points[items[0].dataIndex]?._id ? label(points[items[0].dataIndex]._id) : '', label: context => money(context.parsed.y), afterLabel: context => `${points[context.dataIndex]?.count || 0} completed order(s)` } } }, scales: { x: { grid: { display: false }, border: { display: false }, ticks: { color: '#8b9892', font: { size: 11 }, maxTicksLimit: 7 } }, y: { beginAtZero: true, border: { display: false }, grid: { color: 'rgba(22, 87, 65, .08)' }, ticks: { color: '#8b9892', font: { size: 11 }, callback: value => money(value) } } } };
  if (loading) return <div className="loading-container">Loading live analytics…</div>;
  const cards = [{ icon: FiDollarSign, label: 'Total sales', value: money(revenue), note: `Last ${range} days`, color: '#168064' }, { icon: FiShoppingCart, label: 'Completed orders', value: orders, note: 'Delivered purchases', color: '#4379bf' }, { icon: FiTrendingUp, label: 'Average order', value: money(average), note: 'Completed orders only', color: '#c8871b' }, { icon: FiUsers, label: 'Customers', value: users, note: `${products} products in catalogue`, color: '#7c5bbd' }];
  return <main className="admin-dashboard"><header className="dashboard-header"><div><span>BUSINESS OVERVIEW</span><h1>Sales analytics</h1><p>Completed orders and revenue performance.</p></div><button className="refresh-btn" onClick={load}><FiRefreshCw /> Refresh data</button></header>{error && <p className="dashboard-error">{error}</p>}<section className="stats-grid">{cards.map(({ icon: Icon, ...card }) => <article className="stat-card" key={card.label}><i style={{ background: `${card.color}17`, color: card.color }}><Icon /></i><div><small>{card.label}</small><strong>{card.value}</strong><span>{card.note}</span></div></article>)}</section><section className="chart-container"><header className="chart-header"><div><span>REVENUE PERFORMANCE</span><h2>Sales analytics <em>· Daily</em></h2><p>{points.length ? `${money(revenue)} from ${orders} completed order${orders === 1 ? '' : 's'}` : 'Completed sales will appear here.'}</p></div><select value={range} onChange={event => setRange(Number(event.target.value))} aria-label="Sales date range"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></header><div className="chart-wrapper">{points.length ? <Line data={chartData} options={options} /> : <div className="chart-empty"><FiTrendingUp /><h3>No completed sales yet</h3><p>Approve an order and it will appear here after delivery completes.</p></div>}</div></section></main>;
};
